addpath('../controllers');
addpath('../solvers');
addpath('../trajectory_generator');
addpath('../classes');
addpath('../utilities');
addpath('../');
addpath('../../matlab_utils/src/');
addpath('../structs_rosbagsData/');
addpath('../transform_estimator/');
